### ISSUE TITLE
nutra-babel enoent, temp file not created

### ISSUE THREAD

**Issue by moshmage** [m-a-r-c-e-l-i-n-o/nutra-jasmine-coverage-babel-preset#1]
I'm on windows, if that matters (can be one of those "path too long" problems, but it doesnt seem so. Can also be related to spaces on my windows username. i really don't know.

```logtalk
Error: ENOENT: no such file or directory, open 'C:\Users\Mosh Mage\WebstormProjects\TSPT\node_modules\nutra\tmp\RlvrosrQ4NQu\babel\server-specs|specs|map-class-spec.js'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.writeFileSync (fs.js:1156:15)
    at Object.createFileSync (C:\Users\Mosh Mage\WebstormProjects\TSPT\node_modules\fs-extra\lib\ensure\file.js:34:6)
    at events.onFileLoad (C:\Users\Mosh Mage\WebstormProjects\TSPT\node_modules\nutra-babel\dist\nutra-babel.js:55:27)
    at hooks.reduce.source (C:\Users\Mosh Mage\WebstormProjects\TSPT\node_modules\nutra\dist\nutra.js:290:26)
    at Array.reduce (native)
    at Private.runPreprocessorOnFileLoadHooks (C:\Users\Mosh Mage\WebstormProjects\TSPT\node_modules\nutra\dist\nutra.js:288:27)
    at Private.onFileSourceLoaded (C:\Users\Mosh Mage\WebstormProjects\TSPT\node_modules\nutra\dist\nutra.js:260:21)
    at C:\Users\Mosh Mage\WebstormProjects\TSPT\node_modules\nutra-commonjs\dist\nutra-commonjs.js:25:55

```

`nutra.conf.js`

```js
module.exports = function( config ) {
    config.set({
        frameworks: ['nutra-jasmine'],
        files: ['server-specs/specs/**/*.js', 'server-dev/!(server)/*.js'],
        preprocessors: {
            'server-specs/specs/**/*.js': ['nutra-babel'], 
            'server-dev/!(server)/*.js': ['nutra-babel', 'nutra-coverage']
        },
        reporters: ['nutra-coverage'],
        babelOptions: {
            configFile: './.babelrc'
        },
        coverageOptions: {
            reporters: [
                { type: 'html', subdir: '.' }
            ]
        }
    });
};```

**Comment by m-a-r-c-e-l-i-n-o** [comment]
@moshmage I do apologize, for now I am only focusing on Linux, but I do plan on supporting Windows in the near future, I'll keep you posted. Feel free to submit a pr meanwhile! It's likely related to: https://github.com/m-a-r-c-e-l-i-n-o/nutra/issues/1

**Comment by moshmage** [comment]
No problemo, Marcellino [I'll close this and get my findings there](https://github.com/m-a-r-c-e-l-i-n-o/nutra/issues/1#issuecomment-258032718)
